#include<iostream>
using namespace std;
int main()
{
    int month;
    cin>>month;

    if(month==1)
    {
        cout<<"January"<<endl;
    }
    if(month==2)
    {
        cout<<"February"<<endl;
    }
    if(month==3)
    {
        cout<<"March"<<endl;
    }
    if(month==4)
    {
        cout<<"April"<<endl;
    }
    if(month==5)
    {
        cout<<"May"<<endl;
    }
    if(month==6)
    {
        cout<<"June"<<endl;
    }
    if(month==7)
    {
        cout<<"July"<<endl;
    }
    if(month==8)
    {
        cout<<"August"<<endl;
    }
    if(month==9)
    {
        cout<<"September"<<endl;
    }
    if(month==10)
    {
        cout<<"October"<<endl;
    }
    if(month==11)
    {
        cout<<"November"<<endl;
    }
    if(month==12)
    {
        cout<<"December"<<endl;
    }
}
